services:
  - type: web
    name: bitedrop-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn configuration.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bitedrop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    plan: free
    autoDeploy: true
databases:
  - name: bitedrop-db
    plan: free
