version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bitedrop_db
      POSTGRES_USER: bitedrop_user
      POSTGRES_PASSWORD: bitedrop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
