# Generated by Django 5.2.7 on 2025-10-07 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
        (
            "user_account",
            "0002_rename_mobile_user_phone_remove_user_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="restaurant.restaurant",
            ),
        ),
    ]
