# Generated by Django 5.2.7 on 2025-10-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0003_user_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
